name: Docker with QEMU

on:
  workflow_dispatch:
    inputs:
      nim_version:
        description: Nim version (2.0.14)
        required: true
        type: string
      platforms:
        description: Platforms (linux/amd64,linux/arm64)
        required: false
        type: string
        default: linux/amd64,linux/arm64

env:
  DOCKER_FILE: Dockerfile
  DOCKER_REPO: codexstorage/nim-lang
  PLATFORMS: ${{ inputs.platforms }}
  NIM_VERSION: ${{ inputs.nim_version }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.NIM_VERSION }}
          build-args: |
            NIM_VERSION=${{ env.NIM_VERSION }}
